on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
  
jobs:
  print-username:
    runs-on: ubuntu-latest
    env:
      operator: ${{ github.event.inputs.username }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: condition 1
        if: "contains(github.event.inputs.username, 'BINA')"
        run: echo 'BUSSR'
        
      -  name: Check with operator
         run: |
           oper1=$(grep $operator list)
           echo $oper1
           
      -  name: Compare  
         if: "contains(github.event.inputs.username, '$oper1')"
         run: echo sucess
    
      -  name: Print the input name to STDOUT
         run: echo The username is ${{ github.event.inputs.username }}
        
  after-deploy:
    runs-on: ubuntu-latest
    needs: [print-username]
    if: github.event.inputs.username == 'BUSSR'
    steps:
      - name: chell
        run: echo sucess
        
      
    
