on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
  
jobs:
  job1:
      runs-on: ubuntu-latest
      env:
        operator: ${{ github.event.inputs.username }}
      outputs:
        output1: ${{ steps.step1.outputs.test }}
    
      steps:
    
      - id: step1
        run: echo "::set-output name=test::$oper1"
      - id: step2
        run: echo "::set-output name=test::world"
      
      - name: Checkout
        uses: actions/checkout@v2
        
 
        
      - name: condition 1
        if: "contains(github.event.inputs.username, 'BINA')"
        run: echo 'BUSSR'
        
      -  name: Check with operator
         run: |
           oper1=$(grep $operator list)
           echo $oper1
           
      -  name: Compare  
         run: echo sucess
    
      -  name: Print the input name to STDOUT
         run: echo The username is ${{ github.event.inputs.username }}
        
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: github.event.inputs.username == 'BUSSR'
    steps:
      - name: chell
        run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
        
      
    
