on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Test input'
        required: true

  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "FOO: $MY_VAR"
        shell: bash
        env:
          MY_VAR: ${{ inputs.foo }} 
      
    
